#!/bin/bash

echo "Firebase Profile Setup Instructions"
echo "===================================="
echo ""
echo "1. First, make sure you're logged in to Firebase CLI:"
echo "   firebase login"
echo ""
echo "2. Select your Firebase project:"
echo "   firebase use <your-project-id>"
echo ""
echo "3. Deploy Firestore security rules:"
echo "   firebase deploy --only firestore:rules"
echo ""
echo "4. Your profile data will now be saved to Firestore!"
echo ""
echo "Security Rules Applied:"
echo "- Users can only read/write their own profile data"
echo "- Authentication is required"
echo "- Profile data is stored in 'profiles' collection"
echo ""
echo "Profile Features:"
echo "- Multiple academic qualifications support"
echo "- Automatic save/load on login"
echo "- Secure per-user data storage"