const CHUNK_PUBLIC_PATH = "server/app/api/flashcards/sessions/route.js";
const runtime = require("../../../../chunks/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/a0d31_next_944cc1._.js");
runtime.loadChunk("server/chunks/c1962_@auth_core_75e918._.js");
runtime.loadChunk("server/chunks/990b6_jose_dist_node_esm_918d3a._.js");
runtime.loadChunk("server/chunks/node_modules__pnpm_3eff7c._.js");
runtime.loadChunk("server/chunks/[root of the server]__ab3e11._.js");
runtime.loadChunk("server/chunks/_3146d1._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/api/flashcards/sessions/route/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@15.1.6_@opentelemetry+api@1.9.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/flashcards/sessions/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
